### ISSUE TITLE
Practica 5 Diseño de control personalizado

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-FedericoVictorianoSierra#2]
El estudiante debe realizar una practica 5 para realizar la implementación de un componente personalizado para su implementación como control en Visual Studio.  

1. Visualizar el video en Youtube para realizar la practica del control personalizado

https://www.youtube.com/watch?v=a5SM5mrqb5s

3. Leer el siguiente articulo para  implementar el control personalizado.

https://rjcodeadvance.com/toggle-button-custom-controls-winform-c/ 

5. Diseñar una biblioteca DLL para la implementación del control personalizado.
6. Declarar campos y propiedades heredadas de un control nativo de Visual Studio
7. Compilar la biblioteca para poder reutilizarla en nuevos proyectos de Visual Studio.
8. Realizar una aplicación de escritorio utilizando la nueva aplicación de escritorio.

**Comment by FedericoVictorianoSierra** [comment]
[Practica 5 (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-FedericoVictorianoSierra/files/8312077/Practica.5.Federico.Victoriano.Sierra.4US.pdf)

**Comment by OFELHER93** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
